# Generated by Django 5.1.7 on 2025-04-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID for billing.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe Subscription ID.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete'), ('past_due', 'Past Due')], help_text="Status of the user's Stripe subscription.", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', help_text="User's current subscription tier.", max_length=10),
        ),
    ]
