# Generated by Django 5.1.7 on 2025-04-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_customuser_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription_tier',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('pro', 'Pro')], help_text="User's current subscription tier.", max_length=10, null=True),
        ),
    ]
