# Generated by Django 5.1.7 on 2025-04-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_alter_customuser_subscription_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_chat_messages',
            field=models.PositiveIntegerField(default=0, help_text='Number of chat messages sent in the current period.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_post_generations',
            field=models.PositiveIntegerField(default=0, help_text='Number of posts generated in the current period.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_post_submissions',
            field=models.PositiveIntegerField(default=0, help_text='Number of posts submitted/published in the current period.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_recording_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Total minutes recorded in the current period.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_recordings',
            field=models.PositiveIntegerField(default=0, help_text='Number of recordings made in the current period.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscription_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete'), ('past_due', 'Past Due'), ('pending_payment', 'Pending Payment'), ('trialing', 'Trialing')], help_text="Status of the user's Stripe subscription.", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscription_tier',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('pro', 'Pro')], help_text="User's current subscription tier.", max_length=10, null=True),
        ),
    ]
