# Generated by Django 5.1.7 on 2025-04-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_customuser_current_chat_messages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rate_limit_last_reset',
            field=models.DateField(blank=True, help_text='Date when usage counters were last reset.', null=True),
        ),
    ]
