# Generated by Django 5.1.7 on 2025-04-28 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_customuser_rate_limit_last_reset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='current_recording_minutes',
        ),
    ]
