# Generated by Django 5.1.7 on 2025-04-02 02:47

import django.db.models.deletion
import pgvector.django.vector
import taggit.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brain_dump_app', '0001_add_pgvector_extension'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainDump',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('recording', models.FileField(upload_to='recordings/')),
                ('transcription', models.TextField(blank=True)),
                ('raw_hashtags', models.TextField(blank=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536, null=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Brain Dump',
                'verbose_name_plural': 'Brain Dumps',
            },
        ),
    ]
