# Generated by Django 5.1.7 on 2025-04-03 01:36

import pgvector.django.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain_dump_app', '0002_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='braindump',
            index=pgvector.django.indexes.IvfflatIndex(fields=['embedding'], lists=100, name='embedding_ivf_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
