# Generated by Django 5.1.7 on 2025-04-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain_dump_app', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='braindump',
            name='edited',
            field=models.BooleanField(default=False, help_text='Whether the transcription has been edited by the user manually.'),
        ),
    ]
