# Generated by Django 5.1.7 on 2025-04-06 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain_dump_app', '0005_braindump_edited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth2_access_token', models.TextField(blank=True, null=True)),
                ('oauth2_refresh_token', models.TextField(blank=True, null=True)),
                ('twitter_user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('twitter_username', models.CharField(blank=True, max_length=50, null=True)),
                ('twitter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twitter_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
