# Generated by Django 5.1.7 on 2025-04-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain_dump_app', '0007_oauthstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterconnection',
            name='expires_at',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitterconnection',
            name='expires_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitterconnection',
            name='scope',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twitterconnection',
            name='token_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
