# Generated by Django 5.1.7 on 2025-04-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain_dump_app', '0008_twitterconnection_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthstate',
            name='code_verifier',
            field=models.CharField(max_length=255),
        ),
    ]
