# Generated by Django 5.1.7 on 2025-04-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain_dump_app', '0009_alter_oauthstate_code_verifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brain_dump',
            field=models.ManyToManyField(blank=True, null=True, to='brain_dump_app.braindump'),
        ),
        migrations.AlterField(
            model_name='twitterconnection',
            name='expires_at',
            field=models.FloatField(blank=True, help_text='Timestamp when the refresh token expires', null=True),
        ),
        migrations.AlterField(
            model_name='twitterconnection',
            name='expires_in',
            field=models.IntegerField(blank=True, help_text='Access token expiration time in seconds', null=True),
        ),
    ]
