# Generated by Django 5.1.7 on 2025-04-21 06:57

import brain_dump_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain_dump_app', '0010_post_brain_dump_alter_twitterconnection_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='braindump',
            name='recording',
            field=models.FileField(upload_to=brain_dump_app.models.recording_upload_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
