# Generated by Django 5.1.7 on 2025-04-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain_dump_app', '0011_remove_post_updated_at_alter_braindump_recording_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterconnection',
            name='char_limit',
            field=models.IntegerField(default=280, help_text='Character limit for the user. 280 for free users, 25000 for paid subscribers'),
        ),
        migrations.AddField(
            model_name='twitterconnection',
            name='verified',
            field=models.BooleanField(default=False, help_text='Whether the account is verified on twitter'),
        ),
    ]
