# Generated by Django 5.1.7 on 2025-04-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain_dump_app', '0012_twitterconnection_char_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=20),
        ),
    ]
