# Generated by Django 5.1.7 on 2025-05-04 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain_dump_app', '0014_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='braindump',
            name='tags',
        ),
    ]
