# Generated by Django 5.1.7 on 2025-05-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain_dump_app', '0015_remove_braindump_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterconnection',
            name='oauth1_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitterconnection',
            name='oauth1_access_token_secret',
            field=models.TextField(blank=True, null=True),
        ),
    ]
