# Generated by Django 5.1.7 on 2025-05-15 03:11

import brain_dump_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain_dump_app', '0016_twitterconnection_oauth1_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterconnection',
            name='oauth1_access_token',
            field=brain_dump_app.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twitterconnection',
            name='oauth1_access_token_secret',
            field=brain_dump_app.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twitterconnection',
            name='oauth2_access_token',
            field=brain_dump_app.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twitterconnection',
            name='oauth2_refresh_token',
            field=brain_dump_app.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
