# Generated by Django 5.1.7 on 2025-05-18 16:02

import brain_dump_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain_dump_app', '0017_alter_twitterconnection_oauth1_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='braindump',
            name='transcription',
            field=brain_dump_app.fields.EncryptedTextField(blank=True),
        ),
    ]
